### ISSUE TITLE
Некорректное удаление данных

### ISSUE THREAD

**Issue by Anastasia-8** [VladimirSinitsin/tg_finance-helper#3]
При выполнении команды по удалению базы данных, удаляются также и категории с продуктами. Из-за этого при добавлении известного продукта приходится заново указывать категорию.

Ожидаемое поведение: удаляются сами расходы, а не вся база данных (возможно выделить в отдельную команду), но при этом бот помнит, какой категории принадлежит известный продукт.

**Comment by VladimirSinitsin** [comment]
Исправлено в коммите: https://github.com/VladimirSinitsin/tg_finance-helper/commit/a1f97ced3960877397178a5d4175e7253dc86565
Функции удаления платежей и доходов вынесены в отдельные.
