### ISSUE TITLE
Не добавляется новая категория.

### ISSUE THREAD

**Issue by Anastasia-8** [VladimirSinitsin/tg_finance-helper#5]
Если добавлять продукт, категория которого уже известна, но надо её указать, то бот этого не делает, предлагая лишь добавить новую.

Ожидаемое поведение: спросить в какую из известных категорий добавить продукт, либо попросить ввести новую.

**Comment by VladimirSinitsin** [comment]
Исправлено с релизом: bfd9c1a83b1569a482fea4744cbf406df65a9c62
